name: g14
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  video_player: ^2.8.1
  intl: ^0.18.1
  table_calendar: ^3.0.9
  html: ^0.15.4
  http: ^1.1.0
  shared_preferences: ^2.2.2
  youtube_player_iframe: ^4.0.4
  cloud_firestore: ^4.12.0
  youtube_api: ^1.0.4
  cupertino_icons: ^1.0.6
  rive: ^0.11.4
  flutter_svg: ^2.0.7
  riverpod_generator: ^2.3.3
  build_runner: ^2.4.6
  riverpod_annotation: ^2.2.1
  go_router: ^11.1.4
  flutter_riverpod: ^2.4.4
  google_sign_in: ^6.1.5
  firebase_auth: ^4.11.0
  flutter_native_splash: ^2.3.4
  flutter:
    sdk: flutter




  firebase_core: ^2.20.0
  font_awesome_flutter: ^10.6.0

dependency_overrides:
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/avaters/
    - assets/Backgrounds/
    - assets/icons/
    - assets/images/
    - assets/RiveAssets/
    - assets/gif/road.gif

  uses-material-design: true

flutter_native_splash:
  color: "#fffffc"
  image: assets/images/appicon2.png
  android: true
  ios: true
  web: true
  resize_mode: contain
  android_gravity: center
  ios_content_mode: scaleAspectFit
  web_image_mode: center
  fullscreen: true
